
import './styles/index.scss'
import './styles/globals.css'

import type { Metadata } from 'next'
// import { Inter } from 'next/font/google'
import localFont from 'next/font/local'
// const inter = Inter({ subsets: ['latin'] })
const localF = localFont({ src: './fonts/Poppins/Poppins-Regular.ttf' })
 
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={localF.className}>{children}</body>
    </html>
  )
}
